// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using notip_server.Data;

#nullable disable

namespace notip_server.Migrations
{
    [DbContext(typeof(DbChatContext))]
    [Migration("20240428034600_UpdateDb2")]
    partial class UpdateDb2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("notip_server.Models.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("GroupCallCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("GroupCallCode");

                    b.HasIndex("UserCode");

                    b.ToTable("Call", (string)null);
                });

            modelBuilder.Entity("notip_server.Models.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ContactCode");

                    b.HasIndex("UserCode");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("notip_server.Models.Group", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComment("single: chat 1-1\r\nmulti: chat 1-n");

                    b.HasKey("Code");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("notip_server.Models.GroupCall", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComment("single: chat 1-1\r\nmulti: chat 1-n");

                    b.HasKey("Code");

                    b.ToTable("GroupCall", (string)null);
                });

            modelBuilder.Entity("notip_server.Models.GroupUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("GroupCode");

                    b.HasIndex("UserCode");

                    b.ToTable("GroupUser", (string)null);
                });

            modelBuilder.Entity("notip_server.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasComment("text\r\nmedia\r\nattachment");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GroupCode");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("notip_server.Models.User", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Avatar")
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<string>("CurrentSession")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Dob")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Code");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("notip_server.Models.Call", b =>
                {
                    b.HasOne("notip_server.Models.GroupCall", "GroupCall")
                        .WithMany("Calls")
                        .HasForeignKey("GroupCallCode")
                        .IsRequired()
                        .HasConstraintName("FK_Call_GroupCall");

                    b.HasOne("notip_server.Models.User", "User")
                        .WithMany("Calls")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("FK_Call_User");

                    b.Navigation("GroupCall");

                    b.Navigation("User");
                });

            modelBuilder.Entity("notip_server.Models.Contact", b =>
                {
                    b.HasOne("notip_server.Models.User", "UserContact")
                        .WithMany("Contacts")
                        .HasForeignKey("ContactCode")
                        .IsRequired()
                        .HasConstraintName("FK_Contact_User1");

                    b.HasOne("notip_server.Models.User", "User")
                        .WithMany("ContactUsers")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("FK_Contact_User");

                    b.Navigation("User");

                    b.Navigation("UserContact");
                });

            modelBuilder.Entity("notip_server.Models.GroupUser", b =>
                {
                    b.HasOne("notip_server.Models.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupCode")
                        .IsRequired()
                        .HasConstraintName("FK_GroupUser_Group");

                    b.HasOne("notip_server.Models.User", "User")
                        .WithMany("GroupUsers")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("FK_GroupUser_User");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("notip_server.Models.Message", b =>
                {
                    b.HasOne("notip_server.Models.User", "UserCreatedBy")
                        .WithMany("Messages")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Message_User");

                    b.HasOne("notip_server.Models.Group", "Group")
                        .WithMany("Messages")
                        .HasForeignKey("GroupCode")
                        .IsRequired()
                        .HasConstraintName("FK_Message_Group");

                    b.Navigation("Group");

                    b.Navigation("UserCreatedBy");
                });

            modelBuilder.Entity("notip_server.Models.Group", b =>
                {
                    b.Navigation("GroupUsers");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("notip_server.Models.GroupCall", b =>
                {
                    b.Navigation("Calls");
                });

            modelBuilder.Entity("notip_server.Models.User", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("ContactUsers");

                    b.Navigation("Contacts");

                    b.Navigation("GroupUsers");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
